### ISSUE TITLE
Is it working with 5.2

### ISSUE THREAD

**Issue by 0xb0c4n** [bobost2/MySQL-UnrealEngine-Plugin#1]
Hello,

is this plugin supposed to work with UE 5.2 ?

Good day

**Comment by bobost2** [comment]
Hello,
I tried to rebuild it in 5.2.1 and to my surprise it works (compiles). I haven't actually tested it, because I don't have an active database, but my guess is that it would probably work just fine.

_Just keep in mind that this plugin is not intended for production (as noted in README), because your code might get reversed engineered and your database could get compromised. Also I don't plan to continue development on this plugin, since it was just an old school project._

Have a great day too!
